### ISSUE TITLE
README.md suggests invalid command line argument `yt`

### ISSUE THREAD

**Issue by xobs** [Microsoft/pxt-chibitronics#243]
The `README.md` instructions say to run `pxt serve -yt` to debug `.cpp` files.  However, this doesn't work:

```powershell
[12:33:55 PM] ~/Documents/Code/Makecode/pxt-chibitronics> pxt serve -yt
Using target chibitronics with build engine platformio
  target: v C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics
  pxt-core: v C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\pxt-core
INTERNAL ERROR: Error: Unrecognized flag 'yt' for command 'serve'
    at CommandParser.parseCommand (C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\pxt-core\built\commandparser.js:73:27)
    at C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\pxt-core\built\pxt.js:135740:18
    at tryCatcher (C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\smcro\Documents\Code\Makecode\pxt-chibitronics\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```

This is with the latest HEAD, using pxt installed with `npm install -g pxt` as per the `README.md`.

**Comment by xobs** [comment]
Apparently the flag is `pxt serve --local`.  The `--local` flag should be documented, and `README.md` should be updated.
